const Strings = {
    email: 'Your Email',
    password: 'Password',
    forgotpassword:"Forgot Password",
    emailplaceholder: 'Enter your Email',
    passwordplaceholder: '**********',
    login:"Log in",
    donthaveaccount:"Don't have an account?",
    signup:"Sign up",
    createacc:"Create your account!",
    firstnamem:"Enter your Firstname",
    firstname:"Firstname",
    lastnamem:"Enter last name",
    lastname:"Lastname",
    usernamem:"Create username",
    usernamelaceholder:"Enter your username",
    forgotscreentitle:"Oops! Let’s get a new password.",
    username:"Username",
    passwordm:"Create password", 
    passwordnewm:"Create new password", 
    emailm:"Enter email address",
    phonem:"Enter your phone number",
    phoneno:"Phone No",
    dobm:"mm//dd//yy",
    dob:"DOB",
    locationm:"city,state",
    location:"Location",
    confirmpassword:"Confirm Password",
    confirmpasswordm:"Re Enter password",
    forgotheading:"Enter phone number to receive your 6-digit verification code",
    sendverification:"Send verification code",
    enter6digits:"Enter 6-digit verification code",
    submit:"Submit",
    enternewpassword:"Enter new password"
  };
  export default Strings;
  